# CICD Demo !
version: 2
orbs:
  python: circleci/python@0.2.1

jobs:
  test-model:
    executor: machine
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run: sh predictModelTest.sh
      
  build-model:
    executor: machine
    steps:
      - checkout
      - run: sh predictModelBuild.sh
  test-build:
    executor: machine
    steps:
      - checkout
      - run: sh predictModelTestBuild.sh

  export-model-to-ECR:
    executor: machine
    steps:
      - checkout
      - run: sh predictModelExport.sh

      
workflows:
  version: 2
  main:
    jobs:
      - test-model
      - build-model:
          requires:
            - test-model
      - test-build:
          requires:
            - build-model 
      - export-model-to-ECR:
          requires:
            - test-model
            - build-model
            - test-build
