version: 2
orbs:
  python: circleci/python@0.2.1

jobs:
  test_model:
    executor: machine
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run: python predictModelTest.py 1 10  
  test_model:
    executor: machine
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run: python predictModelTest.py 11 20 
workflows:
  version: 2
  one_and_two:
    jobs:
      - test_model
      - two:
          requires:
            - test_model
