version: 2
orbs:
  python: circleci/python@0.2.1

jobs:
  test-model:
    executor: machine
    steps:
      - checkout
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run: python predictModelTest.py 1 10  
      
  build-model:
    executor: machine
    steps:
      - checkout
      - run: python predictModelTest.py 11 20
  test-build:
    executor: machine
    steps:
      - checkout
      - run: python predictModelTest.py 11 20 

  export-model-to-ECR:
    executor: machine
    steps:
      - checkout
      - run: python predictModelTest.py 11 20

      
workflows:
  version: 2
  main:
    jobs:
      - test-model
      - build-model:
          requires:
            - test-model
      - test-build:
          requires:
            - build-model 
      - export-model-to-ECR:
          requires:
            - test_model
            - build-model
            - test-build
